version: '3.8'
services:

  db:
    container_name: db
    networks:
      - backend
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./ddl_scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin4_container
    networks:
      - backend
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  feature_store:
    depends_on:
      - db
    container_name: feature_store_inz
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    image: feature-store-inz
    restart: always
    environment:
      - CONFIG_PATH=config/config.yml
      - CONNECTION_STRING=${CONNECTION_STRING}

volumes:
  db:
    driver: local
  pgadmin:
    driver: local

networks:
  backend:
    driver: bridge
